export type { Attachment } from '@astronote/schemas'
export { localAttachments, refreshAttachmentCatalog, rememberAttachment, forgetAttachment, upload } from './catalog'
export { attachmentResponse, cached, cacheAttachmentContent, openAttachment, removeCachedAttachment, clearCachedAttachments } from './content'
export { embeddedImages } from './embedded-images'
export { embeddedImageSource, embeddedImageId } from './references'
